Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\PAINMASTER\Anaconda3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\PAINMASTER\Anaconda3\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PAINMASTER\Measurement\lib2\FastTwoToneSpectroscopyBase.py", line 127, in _record_data
    self._call_setters(values_group)
  File "C:\Users\PAINMASTER\Measurement\lib2\Measurement.py", line 201, in _call_setters
    self._swept_pars[name][0](value)  # this is setter call, look carefully
  File "C:\Users\PAINMASTER\Measurement\lib2\FastTwoToneSpectroscopyBase.py", line 204, in _adaptive_setter
    self._mw_src.set_output_state("ON")
AttributeError: 'list' object has no attribute 'set_output_state'

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\PAINMASTER\Anaconda3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\PAINMASTER\Anaconda3\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PAINMASTER\Measurement\lib2\FastTwoToneSpectroscopyBase.py", line 127, in _record_data
    self._call_setters(values_group)
  File "C:\Users\PAINMASTER\Measurement\lib2\Measurement.py", line 201, in _call_setters
    self._swept_pars[name][0](value)  # this is setter call, look carefully
  File "C:\Users\PAINMASTER\Measurement\lib2\FastTwoToneSpectroscopyBase.py", line 204, in _adaptive_setter
    self._mw_src.set_output_state("ON")
AttributeError: 'list' object has no attribute 'set_output_state'

